"""
Generates web/parks_data.js from the processed pipeline data.

Run after any pipeline update:
    python web/build_parks_json.py

Output is a plain JS file that defines a global PARKS_DATA array.
Using a .js file (rather than .json + fetch) means the app works when
opened directly from the filesystem (file://) as well as via a server.
"""

import sys
import json
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from shared.config import PROCESSED_DIR
import pandas as pd


def main():
    master   = pd.read_csv(PROCESSED_DIR / "parks_master.csv")
    features = pd.read_csv(PROCESSED_DIR / "parks_features.csv")

    df = features.merge(
        master[["park_code", "lat", "lng", "url", "description",
                "avg_annual_recreationvisits", "n_trails", "total_trail_km"]],
        on="park_code",
    )

    parks = []
    for _, row in df.iterrows():
        parks.append({
            "code":             row["park_code"],
            "name":             row["park_name"],
            "lat":              round(float(row["lat"]),  4),
            "lng":              round(float(row["lng"]),  4),
            "url":              row["url"],
            "description":      str(row["description"])[:220].rstrip() + "…",
            "peak_month":       int(row["peak_month"]),
            "avg_annual_visits": int(row["avg_annual_recreationvisits"]),
            "n_trails":         int(row["n_trails"]),
            "total_trail_km":   round(float(row["total_trail_km"]), 1),
            "crowd_score":       round(float(row["crowd_score"]),       3),
            "challenge_score":   round(float(row["challenge_score"]),   3),
            "roughing_it_score": round(float(row["roughing_it_score"]), 3),
            "wildlife_score":    round(float(row["wildlife_score"]),    3),
            "lushness_score":    round(float(row["lushness_score"]),    3),
            "seasonality_score": round(float(row["seasonality_score"]), 3),
        })

    out = Path(__file__).parent / "parks_data.js"
    with open(out, "w", encoding="utf-8") as f:
        f.write("// Generated by web/build_parks_json.py — do not edit manually\n")
        f.write("// Regenerate: python web/build_parks_json.py\n")
        f.write("const PARKS_DATA = ")
        f.write(json.dumps(parks, indent=2, ensure_ascii=False))
        f.write(";\n")

    print(f"Wrote {len(parks)} parks → {out}")


if __name__ == "__main__":
    main()
