"""
Generates web/parks_data.js from the processed pipeline data.
Run after any pipeline update: python web/build_parks_json.py

Output is a plain JS file that defines a global PARKS_DATA array.
Using a .js file (rather than .json + fetch) means the app works when
opened directly from the filesystem (file://) as well as via a server.
"""

import sys
import json
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))
from shared.config import PROCESSED_DIR
import pandas as pd


# ── Manual imputations for parks with missing dimension scores ─────────────
# These parks returned null from the pipeline due to data gaps (see README):
#
#   caco (Cape Cod)      — roughing_it_score: no NPS-managed camping; RIDB
#                          returned nothing. Day-use seashore, similar to
#                          Indiana Dunes (0.0). Imputed: 0.05.
#
#   cuva (Cuyahoga)      — roughing_it_score: peri-urban day-use park with
#                          minimal NPS camping (hostel + a few backcountry
#                          permit sites added recently). Imputed: 0.08.
#
#   drto (Dry Tortugas)  — challenge_score: flat coral island, no elevation
#                          gain; OSM returned no usable trail geometry.
#                          Difficulty is logistical, not physical. Imputed: 0.03.
#
SCORE_IMPUTATIONS = {
    "caco": {"roughing_it_score": 0.05},
    "cuva": {"roughing_it_score": 0.08},
    "drto": {"challenge_score":   0.03},
}


def get_score(row, col):
    """Return score for col, falling back to manual imputation if null."""
    code = row["park_code"]
    val  = row[col]
    if pd.notna(val):
        return round(float(val), 3)
    imputed = SCORE_IMPUTATIONS.get(code, {}).get(col)
    if imputed is not None:
        return imputed
    raise ValueError(
        f"Missing {col} for {code} with no imputation defined. "
        "Add an entry to SCORE_IMPUTATIONS."
    )


def main():
    master   = pd.read_csv(PROCESSED_DIR / "parks_master.csv")
    features = pd.read_csv(PROCESSED_DIR / "parks_features.csv")

    df = features.merge(
        master[["park_code", "lat", "lng", "url", "description",
                "avg_annual_recreationvisits", "n_trails", "total_trail_km"]],
        on="park_code",
    )

    parks = []
    for _, row in df.iterrows():
        parks.append({
            "code":             row["park_code"],
            "name":             row["park_name"],
            "lat":              round(float(row["lat"]), 4),
            "lng":              round(float(row["lng"]), 4),
            "url":              row["url"],
            "description":      str(row["description"])[:220].rstrip() + "…",
            "peak_month":       int(row["peak_month"]),
            "avg_annual_visits": int(row["avg_annual_recreationvisits"]),
            "n_trails":         int(row["n_trails"]) if pd.notna(row["n_trails"]) else 0,
            "total_trail_km":   round(float(row["total_trail_km"]), 1) if pd.notna(row["total_trail_km"]) else 0.0,
            "crowd_score":      get_score(row, "crowd_score"),
            "challenge_score":  get_score(row, "challenge_score"),
            "roughing_it_score": get_score(row, "roughing_it_score"),
            "wildlife_score":   get_score(row, "wildlife_score"),
            "lushness_score":   get_score(row, "lushness_score"),
            "seasonality_score": get_score(row, "seasonality_score"),
            "water_score":      get_score(row, "water_score"),
            "remote_score":     get_score(row, "remote_score"),
        })

    out = Path(__file__).parent / "parks_data.js"
    with open(out, "w", encoding="utf-8") as f:
        f.write("// Generated by build_parks_json.py — do not edit manually\n")
        f.write("// Regenerate: python build_parks_json.py\n")
        f.write("const PARKS_DATA = ")
        f.write(json.dumps(parks, indent=2, ensure_ascii=False))
        f.write(";\n")

    print(f"Wrote {len(parks)} parks → {out}")


if __name__ == "__main__":
    main()
